on:
  push:
    branches:
      - main

jobs:
  push_markdown_job:
    runs-on: ubuntu-latest
    name: Push Markdown to Notion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push markdown
        uses: ./
        id: push_markdown
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
